// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sltthpkywaoskeouplyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsdHRocGt5d2Fvc2tlb3VwbHlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMDk1MDksImV4cCI6MjA2NDc4NTUwOX0.sC2bToOBihWz02V_PEqsTGqnRQdAPo45qt75HXMAPvk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);